// Generated by CoffeeScript 1.8.0
(function() {
  $.getJSON("data.json", function(visaData) {
    return $.getJSON("ru_country_names.json", function(countryNames) {
      var allCountryCodes, compileLists, makeSeries, mapData, styles;
      mapData = Highcharts.maps['custom/world-highres'];
      allCountryCodes = $.map(mapData.features, function(feature) {
        return feature.properties['iso-a2'];
      });
      styles = {
        internalPassport: {
          name: 'Загранпаспорт не нужен',
          color: '#7f7'
        },
        visaFree: {
          name: 'Виза не нужна',
          color: '#3c3'
        },
        airport: {
          name: 'Оформление в аэропорту',
          color: '#ff7'
        },
        online: {
          name: 'Оформление онлайн',
          color: '#da7'
        },
        schengen: {
          name: 'Шенгенская зона',
          color: '#77f'
        },
        danger: {
          color: '#fcc',
          name: 'Посещение опасно'
        },
        closed: {
          color: '#f77',
          name: 'Въезд закрыт'
        },
        visa: {
          color: '#7bf',
          name: 'Нужна виза'
        },
        other: {
          color: '#eee',
          name: 'Другое'
        }
      };
      compileLists = function() {
        return $.each(visaData, function(country, data) {
          var status;
          if (typeof data === 'string') {
            status = data;
            data = {
              "iso-a2": country
            };
          } else {
            status = data.status;
            data["iso-a2"] = country;
          }
          if (!styles[status].data) {
            styles[status].data = [];
          }
          if (allCountryCodes.indexOf(data['iso-a2']) > -1) {
            allCountryCodes.splice(allCountryCodes.indexOf(data['iso-a2']), 1);
          } else {
            console.log(data['iso-a2']);
          }
          return styles[status].data.push(data);
        });
      };
      compileLists();
      styles.other.data = $.map(allCountryCodes, function(code) {
        return {
          'iso-a2': code
        };
      });
      makeSeries = function() {
        return $.map(styles, function(value, name) {
          return value;
        });
      };
      return $('#map').highcharts('Map', {
        title: {
          text: 'Визовый режим для украинцев-туристов'
        },
        subtitle: {
          text: 'На основании сайта Министерства внешних дел Украины и других источников. Информация для ознакомления.'
        },
        credits: {
          href: 'https://github.com/leonid-shevtsov/visa-map-for-ukrainians',
          text: 'Собрал: Леонид Шевцов',
          position: {
            y: -10
          }
        },
        mapNavigation: {
          enabled: true
        },
        plotOptions: {
          map: {
            allAreas: false,
            joinBy: 'iso-a2',
            tooltip: {
              headerFormat: '',
              pointFormatter: function() {
                return "" + countryNames[this['iso-a2']] + ": <b>" + this.series.name + " " + (this.note || '') + "</b>";
              }
            },
            mapData: mapData,
            events: {
              click: function(e) {
                return window.open("https://ru.wikipedia.org/wiki/" + (encodeURIComponent(countryNames[e.point['iso-a2']])));
              },
              legendItemClick: function() {
                return false;
              }
            }
          }
        },
        series: makeSeries()
      });
    });
  });

}).call(this);
